version: '3.4'

services:
  hello:
    image: hello
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27018:27017